### ISSUE TITLE
Asus ExpertBook P2451FA skipping because failed to open

### ISSUE THREAD

**Issue by nguyenhai97** [mincrmatt12/elan-spi-fingerprint#4]
I tried to build your prototype but for some reason when runing `./prototype udev` it gave me a lot of error about 'skipping because failed to open'. The result come as following
```
./prototype udev
Prototype starting...
Compiled with HKEY values : TP_VID 4f3; TP_PID 3148; ACPI_ID ELAN7001
Got HID entry /sys/devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0/0003:046D:C534.0001/hidraw/hidraw0
skipping because failed to open
Got HID entry /sys/devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.1/0003:046D:C534.0002/0003:046D:4054.0003/hidraw/hidraw2
skipping because failed to open
Got HID entry /sys/devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.1/0003:046D:C534.0002/hidraw/hidraw1
skipping because failed to open
Got HID entry /sys/devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-1/i2c-ASUE1201:00/0018:04F3:3148.0004/hidraw/hidraw3
skipping because failed to open
Failed to detect SPI or HID!
```
I don't have much experience about this kind of work so if you need more info then just tell me

Distro: Fedora 34 Beta
Kernel: 5.11.11-300.fc34.x86_64

**Comment by mincrmatt12** [comment]
It's complaining since it doesn't have permission to open the hidraw interface, try running the prototype as root.

**Comment by nguyenhai97** [comment]
It did work, The only problem now is that it failed to detect SPI or HID
```
Prototype starting...
Compiled with HKEY values : TP_VID 4f3; TP_PID 3148; ACPI_ID ELAN7001
Got HID entry /sys/devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0/0003:046D:C534.0001/hidraw/hidraw0
Got HID entry /sys/devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.1/0003:046D:C534.0002/0003:046D:4054.0003/hidraw/hidraw2
Got HID entry /sys/devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.1/0003:046D:C534.0002/hidraw/hidraw1
Got HID entry /sys/devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-1/i2c-ASUE1201:00/0018:04F3:3148.0004/hidraw/hidraw3
Found TP ID!
Failed to detect SPI or HID!
```

**Comment by mincrmatt12** [comment]
Did you install the udev rules? You should have a device `/dev/spidev<something>` if they're working.

**Comment by nguyenhai97** [comment]
ok it kinda embarrassing now, it start to run alot of ImgCorrection BG now so it seem to work it 14% at the moment, so I guess it will take quite some time to finish

**Comment by mincrmatt12** [comment]
It's not a completion percentage, if it gets to there you should be able to put your finger on the sensor and have it stop. Could you attach the output of the prototype up to the line "Taking background image" please? I'll look it over tomorrow when I get some time.

**Comment by nguyenhai97** [comment]
OK here is the prototype log [my gist](https://gist.github.com/nguyenhai97/33115827ba733a0a930204cc5f99b253). Btw put my finger on the sensor doesn't stop the ImgCorrection BG

**Comment by mincrmatt12** [comment]
Please follow the instructions [here](https://github.com/mincrmatt12/elan-spi-fingerprint/issues/3#issuecomment-808635293)

**Comment by nguyenhai97** [comment]
It did work, thank for your work. Now moving on with the libfprint 😁

**Comment by mincrmatt12** [comment]
Right now these sensors aren't working in my libfprint fork, see mincrmatt12/libfprint#1.

**Comment by nguyenhai97** [comment]
So could I use [DupiDachs folk](https://github.com/DupiDachs/libfprint) instead? I just try to build your and it already said something about fail to link FPimage or something like that

**Comment by mincrmatt12** [comment]
You can certainly try, I haven't looked at it too closely though. I think their fork isn't correctly rotating the images (or more accurately it's rotating them when it shouldn't be) Currently I'm working on rewriting my version of the driver with some upstream changes and part of that rewrite will be adding support for these newer sensors.

**Comment by nguyenhai97** [comment]
Ok I will wait for you new rewrite 😁 btw did you have any info related to elan track point? My laptop have that working with the preinstalled endless os but with newer version that I installed and even fedora, ubuntu it not working at all, xinput not detect it and can't found any problem in dmesg at all, I know this not related to your project but I'm kinda desperate so ☹️

**Comment by DupiDachs** [comment]
You can use my branch. It works and validates if you swipe your finger over the sensor. 

I am still in the process of writing another algorithm based on openCV. With that it should work without swiping...

**Comment by mincrmatt12** [comment]
Just FYI, my rewrite is mostly complete and should work with your sensors (it's apparently working for other similar ones, see mincrmatt12/libfprint#1). Try the `mincrmatt12/elan-spi-new` branch.

**Comment by nguyenhai97** [comment]
Did I need to clone the prototype or just build libfprint with drivers=all are enough

**Comment by mincrmatt12** [comment]
You only need libfprint with `drivers=all` (either from my gh or the official libfprint gitlab since I'm there too now) to try it (make sure you're using the `mincrmatt12/elan-spi-new` branch though)

**Comment by nguyenhai97** [comment]
Not sure how output should look like but it doesn't work for me as before (stop at html stuff), here is my commands and build output: https://paste.ee/p/J3fWh

**Comment by mincrmatt12** [comment]
That looks like it compiled properly but it failed to build the documentation, just build it again with `-D doc=false`

**Comment by nguyenhai97** [comment]
It did build but still fprint-enroll show `Impossible to enroll: GDBus.Error:net.reactivated.Fprint.Error.NoSuchDevice: No devices available`, here is my ninja log https://paste.ee/p/l6ryE

**Comment by nguyenhai97** [comment]
already add the modprobe and udev rule

**Comment by mincrmatt12** [comment]
Do the libfprint examples work? (the things that should be in `build/examples/`)

**Comment by nguyenhai97** [comment]
There are no libfprint in example, there is a libfprint folder, here is all the files in that two folder: https://paste.ee/p/5fP1h

**Comment by mincrmatt12** [comment]
Yes, try running `enroll` then `verify`. Make sure you swipe your finger across the sensor.

**Comment by nguyenhai97** [comment]
it fail to detect the fingerprint: https://paste.ee/p/50mzf

**Comment by mincrmatt12** [comment]
You're sure you're on the correct branch (`git checkout mincrmatt12/elan-spi-new`) and build with `-D drivers=all -D doc=false`?

**Comment by nguyenhai97** [comment]
Sorry for late reply, I'm quite busy at this time. I'm sure that I'm clone the right branch
```
[ndhai@fedorabox libfprint]$ git branch --show-current 
mincrmatt12/elan-spi-new
```
and yes, I do build with `-D drivers=all -D doc=false`

**Comment by nguyenhai97** [comment]
I'm even remove the build dir before run `meson build -D drivers=all -D doc=false`

**Comment by mincrmatt12** [comment]
You might need to run the examples as root for it to work.

**Comment by nguyenhai97** [comment]
Here is the start of log file: https://paste.ee/p/QfbCo, here is the end of the log file: https://paste.ee/p/bY2KP

**Comment by nguyenhai97** [comment]
the between are loop of `entering state x` x is some integer number, full log are quite long so it hard to copy all that and send it to paste services

**Comment by mincrmatt12** [comment]
You have to swipe your finger across the sensor for it to work properly, from your logs it looks like you aren't swiping for long enough (or are doing it too fast for it to register).

**Comment by nguyenhai97** [comment]
it seem kinda working? it said wrote scanned image to enrolled.pgm like this: https://paste.ee/p/r2Zuu
