### ISSUE TITLE
Asus VivoBook S15 X530UN

### ISSUE THREAD

**Issue by nahil1** [mincrmatt12/elan-spi-fingerprint#6]
Device: Asus VivoBook S15 X530UN
OS: Fedora 34
Linux Version: 5.11.21-300.fc34.x86_64

When running the prototype, it gets stuck at Capturing Image. I noticed that  ReadSPIStatus() returns 64 which is why it gets stuck there. Any help is appreciated. Full output of the prototype is [here](https://gist.github.com/NeonDragon1909/98ea42d55e8180975004bfd41ca2adce).

**Comment by mincrmatt12** [comment]
Hmm, the output looks fine up until it tries to capture an image, and the sensor claims to be one of the ones that works on other systems. The only thing that sticks out is that according to the `.inf` file from the windows driver bundle for your laptop this sensor should be getting reset via GPIO, and I haven't implemented that, but other people with systems like that have reported it working for them.

I know this is a bit cliche, but have you tried restarting the machine and running it again? I doubt it'll fix it, but I genuinely have no other ideas as to why it's not working for you.

**Comment by nahil1** [comment]
That did fix it. Processed image looks like a fingerprint so i assume its working properly.

**Comment by nahil1** [comment]
On another note, could you explain how to build and install libfprint? I'm unfamiliar with meson and ninja.

**Comment by mincrmatt12** [comment]
It's a bit like CMake:

```
$ # at the root of the libfprint repo
$ meson build -D drivers=all # generates build folder with name `build`
$ cd build
$ ninja
$ sudo ninja install
```

also, although there is a submodule in this repo for libfprint, I haven't been updating it; you should instead clone `mincrmatt12/elan-spi-new` directly.
